version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: account-postgres
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: UTC
    ports:
      - "5433:5432"
    volumes:
      - account_postgres_data:/var/lib/postgresql/data

volumes:
  account_postgres_data:
